# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=5)),
                ('clan_id', models.PositiveIntegerField()),
                ('members_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('account_id', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('last_battle_time', models.DateTimeField()),
                ('client_language', models.CharField(max_length=5)),
                ('logout_at', models.DateTimeField()),
                ('statistics_random', models.TextField()),
                ('statistics_gm10', models.TextField()),
                ('statistics_gm8', models.TextField()),
                ('statistics_gm6', models.TextField()),
                ('clan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wotclans.Clan')),
            ],
        ),
    ]
