# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wotclans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='color',
            field=models.CharField(default='black', max_length=12),
        ),
        migrations.AddField(
            model_name='clan',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='description_html',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='motto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
