# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wotclans', '0002_auto_20171102_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='clan',
            name='elo_gm_VIII',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='elo_gm_X',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='elo_sh_VI',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='elo_sh_VIII',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='elo_sh_X',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='statistics_sh_defense',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='statistics_skirmishes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='account_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_battle_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='logout_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='statistics_gm10',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='statistics_gm6',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='statistics_gm8',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='statistics_random',
            field=models.TextField(null=True),
        ),
    ]
