# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wotclans', '0004_auto_20171105_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='full_name',
            field=models.CharField(max_length=80),
        ),
    ]
