# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wotclans', '0005_auto_20171122_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_big', models.ImageField(upload_to='logos/')),
                ('logo_small', models.ImageField(upload_to='logos/')),
                ('updated_at', models.DateTimeField(null=True)),
                ('clan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wotclans.Clan')),
            ],
        ),
    ]
