# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wotclans', '0006_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='tag',
            field=models.CharField(default='blank', max_length=5),
            preserve_default=False,
        ),
    ]
