# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wotclans', '0007_logo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_big',
            field=models.ImageField(upload_to='big/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo_small',
            field=models.ImageField(upload_to='small/'),
        ),
    ]
